Update sudoers

diff --git a/sudoers b/sudoers
--- a/sudoers
+++ b/sudoers
@@ -4,12 +4,19 @@
 #
 # sudoers.d update
 
-# curl -fsSL mnopi.com/sudoers | sh
+# curl -fsSL mnopi.com/sudoers | sh  # Will fail (since not valid: sudoers.sh, $PASSWORD or sudoers file)
+# EXPORT=correct curl -fsSL mnopi.com/sudoers | sh  # Will not fail
+# sh -c "$(curl -fksSL https://mnopi.com/sudoers)" # Will not fail and prompt for password
+# curl -fsSL mnopi.com/sudoers | sh  # Only if sudoers.sh, $PASSWORD, or sudoers file
 # curl -fsSL mnopi.com/sudoers | sh -s error
-# curl -fsSL mnopi.com/sudoers | sh -s correct
-# sudo rm /etc/sudoers.sh; curl -fsSL mnopi.com/sudoers | sh
+# curl -fsSL mnopi.com/sudoers | sh -s correct; curl -fsSL mnopi.com/sudoers | sh -s fail  # will not fail since sudoers
+
+## sudo rm -f /etc/sudoers.sh; sudo rm -f /etc/sudoers.d/sudoers; unset PASSWORD
+# curl -fsSL mnopi.com/sudoers | sh  # Will fail
+# sh -c "$(curl -fksSL https://mnopi.com/sudoers)"  # Will not fail
 
 set -eu
+[ ! ${1-} ] || history -d -1 >/dev/null 2>&1 || true
 
 stderr() { [ $? -eq 0 ] || {
   echo
@@ -31,7 +38,7 @@ print() (
   eval "${exit-}"
 )
 
-
+{
   name='sudoers'
   exec 2>"/tmp/${name}"
   trap stderr EXIT
@@ -47,13 +54,13 @@ print() (
   man sudoers | grep -q runcwd || runcwd=''
   SUDOC='/usr/bin/sudo'
   tmp="$(mktemp)"
-  umask=0022
+  UMASK=0022
 
   cat >"${tmp}" <<EOF
 # Auto generated by: ${name}
 
 User_Alias ADMINS = %admin, %sudo, %wheel
-Defaults:ADMINS ${defaults}, umask=${umask}, umask_override${runchroot}${runcwd}
+Defaults:ADMINS ${defaults}, umask=${UMASK}, umask_override${runchroot}${runcwd}
 EOF
 
   test -x "${SUDOC}" || {
@@ -67,34 +74,40 @@ EOF
       # shellcheck source=/etc/sudoers.sh
       . "${file}"
     elif [ "${SUDOC}" ]; then
-      printf '%s' "Enter admin password: "
-      save_state="$(stty -g)"
-      IFS='' read -r PASSWORD
-      stty "${save_state}"
+      msg="$(tty || true)"
+      if [ -t 0 ]; then
+        printf '%s' "Enter admin password: "
+        read -r PASSWORD
+        msg=''
+      fi
     fi
   fi
 
-  echo "${PASSWORD}" | ${SUDOC} ${flag} true || print Incorrect Password: "${PASSWORD}"
-  echo "${PASSWORD}" | ${SUDOC} ${flag} rm -rf /etc/sudoers.d/*
-  [ ! "${SUDOC}" ] || ${SUDOC} -K; echo "${PASSWORD}" | ${SUDOC} ${flag} true || print Incorrect Password: "${PASSWORD}"
-  echo "${PASSWORD}" | ${SUDOC} ${flag} cp "${tmp}" "/etc/sudoers.d/${name}" && print "/etc/sudoers.d/${name}"
+  [ ! "${SUDOC}" ] || ${SUDOC} -K
+
+  echo "${PASSWORD}" | ${SUDOC} ${flag} true || print Incorrect Password: "${PASSWORD:-${msg}}"
+
+  if [ "$(echo "${PASSWORD}" | ${SUDOC} ${flag} cat /etc/sudoers.d/*)" != "$(cat "${tmp}")" ]; then
+    echo "${PASSWORD}" | ${SUDOC} ${flag} rm -rf /etc/sudoers.d/*
+    [ ! "${SUDOC}" ] || ${SUDOC} -K
+    echo "${PASSWORD}" | ${SUDOC} ${flag} true || print Incorrect Password: "${PASSWORD}"
+    echo "${PASSWORD}" | ${SUDOC} ${flag} cp "${tmp}" "/etc/sudoers.d/${name}" && print "/etc/sudoers.d/${name}"
+  fi
   [ ! "${SUDOC}" ] || ${SUDOC} -K; ${SUDOC} true || print Invalid Sudoers Configuration
 
-  umask "${umask}"
+  umask "${UMASK}"
 
   cat >"${tmp}" <<EOF
 # shellcheck shell=sh
 
 # Auto generated by: ${name} 
 
-umask ${umask}
+umask ${UMASK}
 
 # Admin password
 export PASSWORD='${PASSWORD}'
 # Sudo command
 export SUDOC='${SUDOC}'
 EOF
-
-  ${SUDOC} mv "${tmp}" "${file}"
-  print "${file}"
-
+  [ "$(cat "${file}" 2>/dev/null)" = "$(cat "${tmp}")" ] || { ${SUDOC} mv "${tmp}" "${file}"; print "${file}"; }
+}
